language: node_js
node_js:
  - "iojs"
  - "7"
script: 
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip-cleanup: true
  github-token: $GITHUB_PAGES
  keep-history: true
  on:
    branch: master
  