language: node_js
node_js:
  - "iojs"
  - "7"
script: 
  - npm build
  - npm test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $3ed4508993e4561f6704bc5cc449de9be0ebfd5e
  keep-history: true
  on:
    branch: master
  